version: '3.2'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - COMMAND=${COMMAND:-start}
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongo-data:
